.TH "ApiController" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApiController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetApiConfig\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file ApiController.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
