.TH "MysqliQueryTest" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MysqliQueryTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestDelete\fP ()"
.br
.ti -1c
.RI "\fBtestUpdate\fP ()"
.br
.ti -1c
.RI "\fBtestInsert\fP ()"
.br
.ti -1c
.RI "\fBtestSelect\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file MysqliQueryTest.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
