.TH "PageApplicationTest" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageApplicationTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestService\fP ()"
.br
.ti -1c
.RI "\fBtestRegisterpage\fP ()"
.br
.ti -1c
.RI "\fBtestTemplates\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file PageApplicationTest.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
