.TH "Symfony::Components::Yaml::Dumper" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony::Components::Yaml::Dumper \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdump\fP ($input, $inline=0, $indent=0)"
.br
.ti -1c
.RI "\fBdump\fP ($input, $inline=0, $indent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Dumper.php.
.SH "Member Function Documentation"
.PP 
.SS "dump ($input, $inline = \fC0\fP, $indent = \fC0\fP)"Dumps a PHP value to YAML.
.PP
\fBParameters:\fP
.RS 4
\fI$input\fP The PHP value 
.br
\fI$inline\fP The level where you switch to inline YAML 
.br
\fI$indent\fP The level o indentation indentation (used internally)
.RE
.PP
\fBReturns:\fP
.RS 4
string The YAML representation of the PHP value 
.RE
.PP

.PP
Definition at line 31 of file Dumper.php.
.SS "dump ($input, $inline = \fC0\fP, $indent = \fC0\fP)"Dumps a PHP value to YAML.
.PP
\fBParameters:\fP
.RS 4
\fI$input\fP The PHP value 
.br
\fI$inline\fP The level where you switch to inline YAML 
.br
\fI$indent\fP The level o indentation indentation (used internally)
.RE
.PP
\fBReturns:\fP
.RS 4
string The YAML representation of the PHP value 
.RE
.PP

.PP
Definition at line 31 of file Dumper.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
