.TH "Symfony::Components::Console::Output::ConsoleOutput" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony::Components::Console::Output::ConsoleOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSymfony::Components::Console::Output::StreamOutput\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($verbosity=self::VERBOSITY_NORMAL, $decorated=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file ConsoleOutput.php.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($verbosity = \fCself::VERBOSITY_NORMAL\fP, $decorated = \fCnull\fP)"Constructor.
.PP
\fBParameters:\fP
.RS 4
\fI$verbosity\fP The verbosity level (self::VERBOSITY_QUIET, self::VERBOSITY_NORMAL, self::VERBOSITY_VERBOSE) 
.br
\fI$decorated\fP Whether to decorate messages or not (null for auto-guessing) 
.RE
.PP

.PP
Reimplemented from \fBOutput\fP.
.PP
Definition at line 37 of file ConsoleOutput.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
