.TH "Symfony::Components::Console::Helper::HelperInterface" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony::Components::Console::Helper::HelperInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHelper\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetHelperSet\fP (\fBHelperSet\fP $helperSet=null)"
.br
.ti -1c
.RI "\fBgetHelperSet\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file HelperInterface.php.
.SH "Member Function Documentation"
.PP 
.SS "getHelperSet ()"Gets the helper set associated with this helper.
.PP
\fBReturns:\fP
.RS 4
\fBHelperSet\fP A \fBHelperSet\fP instance 
.RE
.PP

.PP
Implemented in \fBHelper\fP.
.SS "getName ()"Returns the canonical name of this helper.
.PP
\fBReturns:\fP
.RS 4
string The canonical name 
.RE
.PP

.PP
Implemented in \fBDialogHelper\fP, and \fBFormatterHelper\fP.
.SS "setHelperSet (\fBHelperSet\fP $helperSet = \fCnull\fP)"Sets the helper set associated with this helper.
.PP
\fBParameters:\fP
.RS 4
\fI$helperSet\fP A \fBHelperSet\fP instance 
.RE
.PP

.PP
Implemented in \fBHelper\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
