.TH "Symfony::Components::Console::Helper::Helper" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony::Components::Console::Helper::Helper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSymfony::Components::Console::Helper::HelperInterface\fP.
.PP
Inherited by \fBDialogHelper\fP, and \fBFormatterHelper\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetHelperSet\fP (\fBHelperSet\fP $helperSet=null)"
.br
.ti -1c
.RI "\fBgetHelperSet\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$helperSet\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Helper.php.
.SH "Member Function Documentation"
.PP 
.SS "getHelperSet ()"Gets the helper set associated with this helper.
.PP
\fBReturns:\fP
.RS 4
\fBHelperSet\fP A \fBHelperSet\fP instance 
.RE
.PP

.PP
Implements \fBHelperInterface\fP.
.PP
Definition at line 40 of file Helper.php.
.SS "setHelperSet (\fBHelperSet\fP $helperSet = \fCnull\fP)"Sets the helper set associated with this helper.
.PP
\fBParameters:\fP
.RS 4
\fI$helperSet\fP A \fBHelperSet\fP instance 
.RE
.PP

.PP
Implements \fBHelperInterface\fP.
.PP
Definition at line 30 of file Helper.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
