.TH "Utopia::Components::Helper::TextHelper" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Helper::TextHelper \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetPureWords\fP ($str)"
.br
.ti -1c
.RI "static \fBtokenize\fP ($str)"
.br
.ti -1c
.RI "static \fBgetStrip\fP ()"
.br
.ti -1c
.RI "static \fBstripHTML\fP ($str='')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file TextHelper.php.
.SH "Member Function Documentation"
.PP 
.SS "static getPureWords ($str)\fC [static]\fP"fetch web page content
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string to be cut
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 40 of file TextHelper.php.
.SS "static getStrip ()\fC [static]\fP"fetch web page content
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 73 of file TextHelper.php.
.SS "static stripHTML ($str = \fC''\fP)\fC [static]\fP"remove spaces, tabs and line breaks on html
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string to be cut
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 95 of file TextHelper.php.
.SS "static tokenize ($str)\fC [static]\fP"fetch web page content
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP string to be cut
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 56 of file TextHelper.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
