.TH "Utopia::Components::Model::MigrationDb" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Model::MigrationDb \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($loginparams)"
.br
.ti -1c
.RI "\fB__call\fP ($name, $arguments)"
.br
.ti -1c
.RI "\fBgetMigrationQuery\fP (\fBSchema\fP $schema, $delete=false)"
.br
.ti -1c
.RI "\fBmigrateSchema\fP (\fBSchema\fP $schema, $delete=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file MigrationDb.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
