.TH "Utopia::Components::Helper::HelperFactory" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Helper::HelperFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__call\fP ($name, $arguments=array())"
.br
.ti -1c
.RI "\fBgetHelpers\fP ($name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file HelperFactory.php.
.SH "Member Function Documentation"
.PP 
.SS "getHelpers ($name)"fetch all helper names
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Definition at line 25 of file HelperFactory.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
