.TH "Utopia::Components::DataParser::Parser" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::DataParser::Parser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUtopia::Components::Core::ComponentRoot\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBisSingleton\fP ()"
.br
.ti -1c
.RI "\fBinitialize\fP ()"
.br
.ti -1c
.RI "\fB__call\fP ($name, $arguments)"
.br
.ti -1c
.RI "\fBregisterEngines\fP ($engines)"
.br
.ti -1c
.RI "\fBpack\fP ($input, $type)"
.br
.ti -1c
.RI "\fBparse\fP ($input, $type='noidea', $args=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file DataParser.php.
.SH "Member Function Documentation"
.PP 
.SS "__call ($name, $arguments)"handles all asXXX() function calls 
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$arguments\fP 
.RE
.PP

.PP
Definition at line 41 of file DataParser.php.
.SS "pack ($input, $type)"entry point for packing data output type is for sure a must to include 
.PP
\fBParameters:\fP
.RS 4
\fI$input\fP 
.br
\fI$type\fP 
.RE
.PP

.PP
Definition at line 91 of file DataParser.php.
.SS "parse ($input, $type = \fC'noidea'\fP, $args = \fCarray()\fP)"entry point for parsing data 
.PP
\fBParameters:\fP
.RS 4
\fI$input\fP 
.br
\fI$type\fP 
.RE
.PP

.PP
Definition at line 118 of file DataParser.php.
.SS "registerEngines ($engines)"registering engines available and their classnames 
.PP
\fBParameters:\fP
.RS 4
\fI$engines\fP 
.RE
.PP

.PP
Definition at line 79 of file DataParser.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
