.TH "Utopia::Components::Core::ComponentRoot" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Core::ComponentRoot \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUtopia::Components::Core::IComponentRoot\fP.
.PP
Inherited by \fBParser\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMinionId\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsummon\fP ()"
.br
.ti -1c
.RI "static \fBgetMinions\fP ()"
.br
.ti -1c
.RI "static \fBgetMinionById\fP ($minion_id)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBOKAY\fP = 200"
.br
.ti -1c
.RI "const \fBDUPLICATED\fP = 201"
.br
.ti -1c
.RI "const \fBNOTFOUND\fP = 404"
.br
.ti -1c
.RI "const \fBNOAUTH\fP = 401"
.br
.ti -1c
.RI "const \fBERROR\fP = -999"
.br
.ti -1c
.RI "const \fBERROR_NA\fP = -2"
.br
.ti -1c
.RI "const \fBERROR_VALIDATION\fP = -1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ComponentRoot.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
