.TH "Utopia::Components::Model::ModelException" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Model::ModelException \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 4 of file ModelException.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
