.TH "Utopia::Components::Core::IComponentRoot" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Core::IComponentRoot \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBComponentRoot\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinitialize\fP ()"
.br
.ti -1c
.RI "\fBgetConfigurations\fP ()"
.br
.ti -1c
.RI "\fBgetDependencies\fP ()"
.br
.ti -1c
.RI "\fBgetErrors\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBisSingleton\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file IComponentRoot.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
