.TH "Utopia::Components::Checker::TypeChecker" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Checker::TypeChecker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUtopia::Components::Checker::IChecker\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecute\fP ($input, $params=array())"
.br
.ti -1c
.RI "\fBisSuccess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file TypeChecker.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
