.TH "Utopia::Components::Model::GenericModel" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Model::GenericModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUtopia::Components::Model::BaseModel\fP, and \fBUtopia::Components::Model::IModel\fP.
.SH "Detailed Description"
.PP 
Definition at line 6 of file GenericModel.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
