.TH "Utopia::Components::Core" 3 "Fri Mar 4 2011" "utopia3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utopia::Components::Core \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBComponentRoot\fP"
.br
.ti -1c
.RI "class \fBDataObject\fP"
.br
.ti -1c
.RI "interface \fBIComponentRoot\fP"
.br
.ti -1c
.RI "class \fBMallocworksException\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
base object for data manipulations 2011-02-20: remove caching functionality to make it more lightweighted and less error prone 
.PP
\fBAuthor:\fP
.RS 4
ycheung 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for utopia3 from the source code.
